/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-3',
  aws_cloud_logic_custom: [
    {
      name: 'legalmapApiService',
      endpoint: 'https://fzbyhtflfl.execute-api.eu-west-3.amazonaws.com/devarnaud',
      region: 'eu-west-3',
    },
  ],
  aws_cognito_identity_pool_id: 'eu-west-3:e1010a2e-17cb-41cd-b6f8-799f7f7cf54f',
  aws_cognito_region: 'eu-west-3',
  aws_user_pools_id: 'eu-west-3_SLL7jPw53',
  aws_user_pools_web_client_id: '4ehc3h3074mpctov0jhb4ot2q8',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'FAMILY_NAME', 'GIVEN_NAME'],
  aws_cognito_mfa_configuration: 'OPTIONAL',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: ['REQUIRES_LOWERCASE', 'REQUIRES_UPPERCASE', 'REQUIRES_NUMBERS'],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
